### ISSUE TITLE
CLR/System.NullReferenceException

### ISSUE THREAD

**Issue by jeypatronum** [AeddGinvael/OracleReplay.Parser#1]
Hi!
Tried to use your code for parse game 4797134423, and have to different exceptions.
First is - NullReferenceException

`Возникло исключение: CLR/System.NullReferenceException
Необработанное исключение типа "System.NullReferenceException" в Oracle.dll: 'Object reference not set to an instance of an object.'
   в Oracle.Packets.DemPacket.ParseEmbeddedPackets(Byte[] data) в D:\VStudio\GitHub\OracleReplay.Parser\src\Oracle\Packets\DemPacket.cs:строка 159
   в Oracle.Packets.DemPacket.ParsePacket(Byte[] data) в D:\VStudio\GitHub\OracleReplay.Parser\src\Oracle\Packets\DemPacket.cs:строка 146
   в Oracle.ReplayParser.DataConveyer(DataPacket packet) в D:\VStudio\GitHub\OracleReplay.Parser\src\Oracle\ReplayParser.cs:строка 130
   в Oracle.ReplayParser.ParseNext() в D:\VStudio\GitHub\OracleReplay.Parser\src\Oracle\ReplayParser.cs:строка 107
   в Oracle.ReplayParser.ParseDemReplay(CancellationToken token) в D:\VStudio\GitHub\OracleReplay.Parser\src\Oracle\ReplayParser.cs:строка 79
   в Oracle.ReplayParser.ParseDemReplay() в D:\VStudio\GitHub\OracleReplay.Parser\src\Oracle\ReplayParser.cs:строка 74
   в Examples.Parser.Runner() в D:\VStudio\GitHub\OracleReplay.Parser\src\Examples\Parser.cs:строка 26
   в Examples.MainClass.Main(String[] args) в D:\VStudio\GitHub\OracleReplay.Parser\src\Examples\Main.cs:строка 13`

**Comment by AeddGinvael** [comment]
fixed https://github.com/AeddGinvael/OracleReplay.Parser/commit/2f2bb4bd0c9fe5d280cb8a148bb751697c41362a
