### ISSUE TITLE
CLR/System.ArgumentException

### ISSUE THREAD

**Issue by jeypatronum** [AeddGinvael/OracleReplay.Parser#2]
Hi! Match 4797134423 again. Your example work correct, but all my dem files for some last day have the same exceptions.

Have this:

`Возникло исключение: CLR/System.ArgumentException
Необработанное исключение типа "System.ArgumentException" в System.Private.CoreLib.dll: 'An item with the same key has already been added. Key: CBodyComponentBaseModelEntity(4)'
   в System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException[T](T key)
   в System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   в System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   в Oracle.Packets.SendTablesPacket.ParseSendTable(Byte[] data, IBitStream stream) в D:\VStudio\GitHub\OracleReplay.Parser\src\Oracle\Packets\SendTablesPacket.cs:строка 157
   в Oracle.ReplayParser.DataConveyer(DataPacket packet) в D:\VStudio\GitHub\OracleReplay.Parser\src\Oracle\ReplayParser.cs:строка 120
   в Oracle.ReplayParser.ParseNext() в D:\VStudio\GitHub\OracleReplay.Parser\src\Oracle\ReplayParser.cs:строка 107
   в Oracle.ReplayParser.ParseDemReplay(CancellationToken token) в D:\VStudio\GitHub\OracleReplay.Parser\src\Oracle\ReplayParser.cs:строка 79
   в Oracle.ReplayParser.ParseDemReplay() в D:\VStudio\GitHub\OracleReplay.Parser\src\Oracle\ReplayParser.cs:строка 74
   в Examples.Parser.Runner() в D:\VStudio\GitHub\OracleReplay.Parser\src\Examples\Parser.cs:строка 26
   в Examples.MainClass.Main(String[] args) в D:\VStudio\GitHub\OracleReplay.Parser\src\Examples\Main.cs:строка 13`

If around it by skipping the same key, parsing can be continued, but after some parsed lines we have  [CLR/System.NullReferenceException](https://github.com/AeddGinvael/OracleReplay.Parser/issues/1)

**Comment by AeddGinvael** [comment]
Hello, thank you for your feedback. Your issues is fixed https://github.com/AeddGinvael/OracleReplay.Parser/commit/2f2bb4bd0c9fe5d280cb8a148bb751697c41362a
