### ISSUE TITLE
Information around Message`MapParser`

### ISSUE THREAD

**Issue by glitch100** [AeddGinvael/OracleReplay.Parser#3]
I was looking to understand how you worked out the mappings in the `PacketParserType`?

I would like to be able to parse `CCLCMsg_RequestPause` along with others?

**Comment by glitch100** [comment]
@AeddGinvael Was just looking for info, happy to chat over another platform if you want?

**Comment by AeddGinvael** [comment]
Hello. 
Actually, this repo is just a port of this [project](https://github.com/skadistats/clarity). 
I got `PacketParserType` mappings from [this](https://github.com/skadistats/clarity-protobuf/blob/master/src/main/java/skadistats/clarity/wire/s2/EmbeddedPackets.java). 
You can ask author of the clarity project, he knows enough about how parsing works.

**Comment by glitch100** [comment]
Thanks
